//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EmpEntities : DbContext
    {
        public EmpEntities()
            : base("name=EmpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Tbl_EmployeeDetails> Tbl_EmployeeDetails { get; set; }
        public DbSet<tbl_MasterTaxSlabs> tbl_MasterTaxSlabs { get; set; }
        public DbSet<tbl_PayDetails> tbl_PayDetails { get; set; }
    
        public virtual ObjectResult<CreatePayslip_Result> CreatePayslip(string fname, string lname, Nullable<int> annualSalary, Nullable<double> superRate, string payStartDate)
        {
            var fnameParameter = fname != null ?
                new ObjectParameter("Fname", fname) :
                new ObjectParameter("Fname", typeof(string));
    
            var lnameParameter = lname != null ?
                new ObjectParameter("Lname", lname) :
                new ObjectParameter("Lname", typeof(string));
    
            var annualSalaryParameter = annualSalary.HasValue ?
                new ObjectParameter("AnnualSalary", annualSalary) :
                new ObjectParameter("AnnualSalary", typeof(int));
    
            var superRateParameter = superRate.HasValue ?
                new ObjectParameter("SuperRate", superRate) :
                new ObjectParameter("SuperRate", typeof(double));
    
            var payStartDateParameter = payStartDate != null ?
                new ObjectParameter("PayStartDate", payStartDate) :
                new ObjectParameter("PayStartDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CreatePayslip_Result>("CreatePayslip", fnameParameter, lnameParameter, annualSalaryParameter, superRateParameter, payStartDateParameter);
        }
    }
}
