//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeePayslips
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PayDetails
    {
        public int PayID { get; set; }
        public Nullable<int> AnnualSalary { get; set; }
        public Nullable<int> SuperRate { get; set; }
    }
}
