//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MasterTaxSlabs
    {
        public int TaxId { get; set; }
        public Nullable<int> SlabStart { get; set; }
        public Nullable<int> SlabEnd { get; set; }
        public Nullable<double> CentPerDollar { get; set; }
        public Nullable<int> Fix { get; set; }
    }
}
